### ISSUE TITLE
Newtonsoft PropertyName Attribute Support

### ISSUE THREAD

**Issue by davemanton** [Gremlinq/ExRam.Gremlinq#1183]
Does Gremlinq support use of Newtonsoft PropertyName attributes?

I'm using CosmosDb with the AspNet nuget packages on the latest version 11

I can't find anything in the samples or documentation and when I attempt to create a simple Vertex it appears to ignore the property names I've defined in the Newtonsoft attributes.  This means when I the object is viewed in the Cosmos Graph viewer a property name would be "Value" instead of the defined "value"

**Comment by rrmistry** [comment]
Attempting to do the same. But unsuccessful so far.

Created a sample Git Repo with latest version `12.0.0-preview.1077` found below:

- My Class definition: [Mammal.cs with Newtonsoft attributes](https://github.com/rrmistry/gremlinq-aspnet-v2/blob/d21fac5278518b6074061ab7f16c613d444a65cf/Elements/Mammal.cs#L18)
- My Program.cs file: [Program.cs with `UseNewtonsoftJson()`](https://github.com/rrmistry/gremlinq-aspnet-v2/blob/d21fac5278518b6074061ab7f16c613d444a65cf/Program.cs#L43)

What I need is to use my own serialization / deserialization logic instead of relying on NewtonSoft:

- My custom serializer: [`JsonHelper.cs`](https://github.com/rrmistry/gremlinq-aspnet-v2/blob/666a64a42342d921cb0ded6b7e17bdcca47683f6/JsonHelper.cs#L32C1-L54C6)

**Comment by danielcweber** [comment]
There is no support for Newtonsoft attributes. [This](https://github.com/Gremlinq/ExRam.Gremlinq/blob/08a82985b40ccc2d5b4f5c43c51af9a7a991c98f/test/Core.Tests/GraphModelTest.cs#L140) might help though.
